### ISSUE TITLE
Project Reports PDF Generation does not seem to work always

### ISSUE THREAD

**Issue by arihakala** [prove/tarantula#8]
I am unable to export "Project Status", "Test Efficiency"and "Prioritized Testing Maturity". I can export all of the other reports. 

Reproducible in pts.tarantula.fi   default project.

https://getsatisfaction.com/prove/topics/does_export_project_status_report_work?utm_content=topic_link&utm_medium=email&utm_source=new_topic

**Comment by iiska** [comment]
Is this still relevant or was it fixed by 127b27501bd430ef76904a66ba6712c0a117a8ea and 83e98d15a1e907de5a4c9d554d33e381c476d227?

**Comment by schlos** [comment]
I can export the Reports to spreadsheet if I am using IE or Firefox. 
I cannot export to XLS using Chrome. 
Exported XLS does not contain updated text from Generated Status Report screen (it exports default values i.e. dd.mm.yyyy).
PDF export still does not work in Chrome, Mozilla and IE11.
Using Tarantula version 2014.26.1 (with no bug tracker linked to Tarantula - not using Jira)

**Comment by yugeshkumar** [comment]
is this issue got fixed? I am still unable to export the report in pdf format.
